### ISSUE TITLE
Galery images

### ISSUE THREAD

**Issue by RavinduSachintha** [FOSS-UCSC/FossCody-1.0#4]
There are 3 images already.

- One image should be change for mentioning that what we are expecting. There should be 3 things somehow.
  - Good Documentation
  - Clear Coding
  - Continuously Contributing

- I suggest, another one image can be just like a simple poster which tells about the competition and the club
- For third one, add some appropriate image for the site

**Comment by Sacheerc** [comment]
"I suggest, another one image can be just like a simple poster which tells about the competition and the club" this may be leads to the duplicate content issue.

**Comment by RavinduSachintha** [comment]
It's just an idea.. Do anything that you think good.

**Comment by Sacheerc** [comment]
Ok.. I got it.

**Comment by Sacheerc** [comment]
Issue Fixed with four slider Images.
